### ISSUE TITLE
Normal无法导入人格模版，报错

### ISSUE THREAD

**Issue by doiss** [wangyu1997/gsuidcore_plugin_chat#3]
python 
![image](https://github.com/wangyu1997/gsuidcore_plugin_chat/assets/97965580/f0a3015f-c104-4a64-b745-155f87fbb375)

nonebot
![image](https://github.com/wangyu1997/gsuidcore_plugin_chat/assets/97965580/e9d0a292-3ec5-495c-8a9c-625526ebbc61)
gsuid-core 
当前最新

报错
![image](https://github.com/wangyu1997/gsuidcore_plugin_chat/assets/97965580/1546e3b3-b40d-4d87-9186-f2c19da3879e)

**Comment by wangyu1997** [comment]
这个问题不是模版没导入 是请求chat失败 如果没有使用国内代理麻烦在config中把proxy置空

**Comment by doiss** [comment]
> 这个问题不是模版没导入 是请求聊天失败 如果没有使用国内代理麻烦在config中把proxy置空

唔QAQ原来是酱紫咩。ok了，灰常感谢ヾ(≧▽≦*)o
